# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "lucid64"
  config.vm.box_url = "http://files.vagrantup.com/lucid64.box"

  config.vm.network :hostonly, "192.168.33.44"

  # Django default port
  config.vm.forward_port 8000, 8000
  # Postgresql
  # config.vm.forward_port 5432, 5432

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  config.vm.share_folder "{{ project_name }}", "/home/vagrant/project", "."

  # Provisioning goes here...

end
